In [8]:
import pandas as pd
import numpy as np
data = pd.read_csv('housing.csv')
data.head() 

data.drop(columns=['Address','Price'],axis=1,inplace=True)  
data.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
0,79545.45857,5.682861,7.009188,4.09,23086.80050
1,79248.64245,6.002900,6.730821,3.09,40173.07217
2,61287.06718,5.865890,8.512727,5.13,36882.15940
3,63345.24005,7.188236,5.586729,3.26,34310.24283
4,59982.19723,5.040555,7.839388,4.23,26354.10947

In [14]:
# Let's apply absolute maximum scaling 
abs_maximum = np.max(np.abs(data),axis=0)
data = data/abs_maximum
data.head() 
# abs_maximum

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
0,0.738572,0.596996,0.651436,0.629231,0.331603
1,0.735816,0.630617,0.625565,0.475385,0.577019
2,0.569044,0.616224,0.791176,0.789231,0.529751
3,0.588154,0.755139,0.519233,0.501538,0.492810
4,0.556929,0.529521,0.728596,0.650769,0.378533

In [15]:
# min-max scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
sacled_data = scaler.fit_tranfrom(data) 
data = pd.DataFrame(scaled_data,columns=data.columns)
data.head()

AttributeError: 'MinMaxScaler' object has no attribute 'fit_tranfrom'

In [ ]:
# Standard Scale